export const authConstant = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  GET_REQUEST: "GET_REQUEST",
  GET_SUCCESS: "GET_SUCCESS",
  GET_FAILURE: "GET_FAILURE",
};

export const kitchenConst = {
  KITCHEN_SIGNUP_REQUEST: "KITCHEN_SIGNUP_REQUEST",
  KITCHEN_SIGNUP_SUCCESS: "KITCHEN_SIGNUP_SUCCESS",
  KITCHEN_SIGNUP_FAILURE: "KITCHEN_SIGNUP_FAILURE",
  KITCHEN_LOGIN_REQUEST: "KITCHEN_LOGIN_REQUEST",
  KITCHEN_LOGIN_SUCCESS: "KITCHEN_LOGIN_SUCCESS",
  KITCHEN_LOGIN_FAILURE: "KITCHEN_LOGIN_FAILURE",
  GET_REQUEST: "GET_REQUEST",
  GET_SUCCESS: "GET_SUCCESS",
  GET_FAILURE: "GET_FAILURE",
  NEWITEM_REQUEST: "NEWITEM_REQUEST",
  NEWITEM_SUCCESS: "NEWITEM_SUCCESS",
  NEWITEM_FAILURE: "NEWITEM_FAILURE",
  GET_KITCHEN_REQUEST: "GET_KITCHEN_REQUEST",
  GET_KITCHEN_SUCCESS: "GET_KITCHEN_SUCCESS",
  GET_KITCHEN_FAILURE: "GET_KITCHEN_FAILURE",
};

export const cartConstants = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",

  REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
  REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
  REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",

  GET_CART_REQUEST: "GET_CART_REQUEST",
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
  GET_CART_FAILURE: "GET_CART_FAILURE",
};

export const orderConst = {
  ORDER_REQUEST: "ORDER_REQUEST",
  ORDER_SUCCESS: "ORDER_SUCCESS",
  ORDER_FAILURE: "ORDER_FAILURE",
  GET_ORDER_REQUEST: "GET_ORDER_REQUEST",
  GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",
  GET_ORDER_FAILURE: "GET_ORDER_FAILURE",
  GET_ALL_ORDER_REQUEST: "GET_ALL_ORDER_REQUEST",
  GET_ALL_ORDER_SUCCESS: "GET_ALL_ORDER_SUCCESS",
  GET_ALL_ORDER_FAILURE: "GET_ALL_ORDER_FAILURE",
  UPDATE_REQUEST: "UPDATE_REQUEST",
  UPDATE_SUCCESS: "UPDATE_SUCCESS",
  UPDATE_FAILURE: "UPDATE_FAILURE",
};

export const paymentConst = {
  BKASH_REQUEST: "BKASH_REQUEST",
  BKASH_SUCCESS: "BKASH_SUCCESS",
  BKASH_FAILURE: "BKASH_FAILURE",
  SSL_REQUEST: "SSL_REQUEST",
  SSL_SUCCESS: "SSL_SUCCESS",
  SSL_FAILURE: "SSL_FAILURE",
};

export const productConst = {
  PRODUCT_REQUEST: "PRODUCT_REQUEST",
  PRODUCT_SUCCESS: "PRODUCT_SUCCESS",
  SHIPPING_SUCCESS: "SHIPPING_SUCCESS",
};
